services:

  api:
    build: .
    container_name: encuestas-api
    ports:
      - "7000:7000"
      - "50051:50051"
    networks:
      - encuestas-net

  frontend:
    image: nginx:alpine
    container_name: encuestas-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    depends_on:
      - api
    networks:
      - encuestas-net

networks:
  encuestas-net:
    driver: bridge